FROM node:8-alpine
RUN apk add --update bash && rm -rf /var/cache/apk/*
RUN npm install nodemon -g
RUN apk update && apk add mysql-client && rm -f /var/cache/apk/*
# set up some directories
RUN mkdir /app
WORKDIR /app
# copy in package.json and install dependencies in your image
COPY package.json /app/
RUN npm install
# copy in frontend source code and set it to run automatically on container launch
COPY app.js /app/
COPY ./public /app/public
COPY ./modules /app/modules
COPY ./test /app/test
EXPOSE 3000
HEALTHCHECK --interval=10s --timeout=3s --start-period=10s CMD wget -qO- http://localhost:3000/api/tasks || exit 1

CMD nodemon app.js -e html,js
